# Generated by Django 5.1.2 on 2025-07-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_room_name_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
